### ISSUE TITLE
Passing an array in CallContext entry

### ISSUE THREAD

**Issue by Johnathon332** [joshstevens19/ethereum-multicall#38]
Hi I am receiving this error when trying to call getAmountsOut on uniswap router

`Error: call revert exception; VM Exception while processing transaction: reverted with reason string "Multicall aggregate: call failed" [ See: https://links.ethers.org/v5-errors-CALL_EXCEPTION ] (method="aggregate((address,bytes)[])", data="0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000204d756c746963616c6c206167677265676174653a2063616c6c206661696c6564", errorArgs=["Multicall aggregate: call failed"], errorName="Error", errorSignature="Error(string)", reason="Multicall aggregate: call failed", code=CALL_EXCEPTION, version=abi/5.6.3)
    at Logger.makeError (/Users/johnathonlam/Documents/work/data-collection/node_modules/@ethersproject/logger/src.ts/index.ts:261:28)
    at Logger.throwError (/Users/johnathonlam/Documents/work/data-collection/node_modules/@ethersproject/logger/src.ts/index.ts:273:20)
    at Interface.decodeFunctionResult (/Users/johnathonlam/Documents/work/data-collection/node_modules/@ethersproject/abi/src.ts/interface.ts:427:23)
    at Object.<anonymous> (/Users/johnathonlam/Documents/work/data-collection/node_modules/@ethersproject/contracts/src.ts/index.ts:400:44)
    at step (/Users/johnathonlam/Documents/work/data-collection/node_modules/@ethersproject/contracts/lib/index.js:48:23)
    at Object.next (/Users/johnathonlam/Documents/work/data-collection/node_modules/@ethersproject/contracts/lib/index.js:29:53)
    at fulfilled (/Users/johnathonlam/Documents/work/data-collection/node_modules/@ethersproject/contracts/lib/index.js:20:58)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  reason: 'Multicall aggregate: call failed',
  code: 'CALL_EXCEPTION',
  method: 'aggregate((address,bytes)[])',
  data: '0x08c379a0000000000000000000000000000000000000000000000000000000000000002000000000000000000000000000000000000000000000000000000000000000204d756c746963616c6c206167677265676174653a2063616c6c206661696c6564',
  errorArgs: [ 'Multicall aggregate: call failed' ],
  errorName: 'Error',
  errorSignature: 'Error(string)',
  address: '0xC50F4c1E81c873B2204D7eFf7069Ffec6Fbe136D',
  args: [
    [
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object], [Object],
      [Object], [Object]
    ]
  ],`

The way I am trying to pass in the data is like

`
{
        reference: info.address + '_' + info.token1,
        contractAddress: chainConfig.bsc.dex.pancakeswap.router,
        abi: uniswapRouterAbi,
        calls: [
          { reference: 'amount', methodName: 'getAmountsOut', methodParameters: [info.token1reserve, [info.token1, chainConfig.bsc.dex.pancakeswap.nativeCurrency]] },
        ],
      }
`

**Comment by joshstevens19** [comment]
Hey please supply me full runnable code will take a look

**Comment by joshstevens19** [comment]
closing as no runable script
